language: node_js
node_js:
- node
cache:
  apt: true
  directories:
  - node_modules
script:
- npm install
- npm install -D @cloudflare/wrangler --registry.npmjs.org
after_script:
- npm run build
- echo ${API_KEY} | npx wrangler config
- npx wrangler publish
