language: node_js
node_js:
- node
cache:
  apt: true
  directories:
  - node_modules
script:
- npm install
- npm install -D @cloudflare/wranger --registry.npmjs.org
after_script:
- npm run build
- echo ${API_KEY} | npx wranger config
- npx wranger publish
